export default result = {
    fruits: [
      {
        name: "Apple",
        image: require("../images/Fruits/Apple.jpg"),
        tags: ["immunity", "physical health", "mental health", "Heart"],
      },
      {
        name: "Orange",
        image: require("../images/Fruits/Orange.jpg"),
        tags: ["immunity", "physical health", "Blood"],
      },
      {
        name: "Kiwi",
        image: require("../images/Fruits/kiwi.jpg"),
        tags: ["immunity", "mental health", "Blood"],
      },
      {
        name: "Strawberry",
        image: require("../images/Fruits/Strawberry.png"),
        tags: ["immunity", "Arthritis"],
      },
      {
        name: "Mango",
        image: require("../images/Fruits/Mango.png"),
        tags: ["immunity", "Vision","Arthritis" ],
      },
      {
        name: "Pineapple",
        image: require("../images/Fruits/Pineapple.png"),
        tags: ["immunity", "mental health"],
      },
      {
        name: "Avacodo",
        image: require("../images/Fruits/Avocado.jpg"),
        tags: ["physical health",'Heart'],
      },
      {
        name: "Blueberries",
        image: require("../images/Fruits/blueberry.jpg"),
        tags: ["physical health",  "Diabetes", "Blood"],
      },
      {
        name: "banana",
        image: require("../images/Fruits/Banana.jpg"),
        tags: ["physical health", "Diabetes"],
      },
      {
        name: "Pomogranate",
        image: require("../images/Fruits/pomogranate.jpg"),
        tags: ["physical health", "Blood", "Heart"],
      },
      {
        name: "Raspberry",
        image: require("../images/Fruits/Raspberry.png"),
        tags: ["mental health","Heart", "Arthritis"],
      },
      {
        name: "lemon",
        image: require("../images/Fruits/lemon.png"),
        tags: ["mental health", "Blood", "Heart", "Arthritis"],
      },
      {
        name: "Grapes",
        image: require("../images/Fruits/Grapes.jpg"),
        tags: ["mental health", "Blood", 'Vision', "Arthritis"],
      },
      {
        name: "Papaya",
        image: require("../images/Fruits/Papaya.jpg"),
        tags: ["Vision", "Diabetes", "Arthritis"],
      },
      {
        name: "Cantaloupe",
        image: require("../images/Fruits/cantaloupe.jpg"),
        tags: ["Vision"],
      },
      {
        name: "Cherry",
        image: require("../images/Fruits/Cherry.jpg"),
        tags: ["Diabetes", "Vision"],
      },
      {
        name: "honrydew",
        image: require("../images/Fruits/honeydew.jpg"),
        tags: ["Diabetes"],
      },
      {
        name: "Tomato",
        image: require("../images/Fruits/Tomato.jpg"),
        tags: ["Vision", "Heart"],
      },
      {
        name: "Watermellon",
        image: require("../images/Fruits/watermellon.jpg"),
        tags: [ "Diabetes"],
      },
    ],
    Vegetables: [
      {
        name: "Spinach",
        vitamins: ["A", "C", "K"],
        minerals: ["iron", "calcium"],
        antioxidants: ["beta-carotene", "lutein"],
        tags: [
          "physical health",
          "Blood",
          "Vision",
          "Arthritis",
          "Diabetes",
          "Heart",
          "immunity",
        ],
        image: require("../images/Vegetables/spinach.png"),
      },
      {
        name: "Broccoli",
        vitamins: ["C", "K"],
        minerals: ["calcium", "iron", "potassium"],
        antioxidants: ["vitamin C", "beta-carotene", "quercetin"],
        tags: [
          "physical health",
          "mental health",
          "Blood",
          "Vision",
          "Arthritis",
          "Diabetes",
          "Heart",
          "immunity",
        ],
        image: require("../images/Vegetables/Broccoli.png"),
      },
      {
        name: "Sweet potato",
        vitamins: ["A", "C"],
        minerals: ["iron", "potassium"],
        antioxidants: ["beta-carotene", "vitamin C"],
        tags: [
          "physical health",
          "mental health",
          "Vision",
          "Arthritis",
          "Heart",
          "immunity",
        ],
        image: require("../images/Vegetables/SweetPotato.png"),
      },
      {
        name: "Bell pepper",
        vitamins: ["C"],
        minerals: ["potassium"],
        antioxidants: ["vitamin C"],
        tags: ["physical health", "Vision", "Heart", "immunity"],
        image: require("../images/Vegetables/bellpepper.png"),
      },
      {
        name: "Carrot",
        vitamins: ["A", "C"],
        minerals: ["potassium"],
        antioxidants: ["beta-carotene"],
        tags: ["physical health", "Blood", "Vision", "Arthritis"],
        image: require("../images/Vegetables/carrots.png"),
      },
      {
        name: "Tomato",
        vitamins: ["C", "K"],
        minerals: ["potassium"],
        antioxidants: ["lycopene", "vitamin C"],
        tags: ["physical health", "mental health", "Blood", "Heart"],
        image: require("../images/Vegetables/tomato.png"),
      },
      {
        name: "Avocado",
        tags: ["mental health"],
        image: require("../images/Vegetables/avocado.png"),
      },
      {
        name: "Beetroot",
        tags: ["Blood"],
        image: require("../images/Vegetables/beetroot.png"),
      },
      {
        name: "Kale",
        tags: ["Blood", "Vision", "Arthritis", "Diabetes", "Heart"],
        image: require("../images/Vegetables/kale.png"),
      },
    ],
    dairy: {},
  };
  